In [75]:
from pulp import *
import numpy as np
import pandas as pd
import re 
import matplotlib.pyplot as plt
from IPython.display import Image
%matplotlib inline

In [76]:
train = []
hrs = []
for i in range(82):
    train.append(i)
    hrs.append(int(np.random.uniform(100,600)))
df = pd.DataFrame({'Train':train,'hour':hrs})
df = df.set_index('Train')
df.to_csv('rawData.csv')
data = pd.read_csv('rawData.csv')
data

    Train  hour
0       0   212
1       1   365
2       2   116
3       3   464
4       4   174
5       5   460
6       6   152
7       7   126
8       8   449
9       9   541
10     10   295
11     11   550
12     12   131
13     13   210
14     14   523
15     15   211
16     16   374
17     17   264
18     18   315
19     19   345
20     20   107
21     21   389
22     22   420
23     23   560
24     24   411
25     25   253
26     26   449
27     27   404
28     28   409
29     29   486
..    ...   ...
52     52   252
53     53   320
54     54   287
55     55   395
56     56   231
57     57   479
58     58   109
59     59   419
60     60   351
61     61   236
62     62   350
63     63   470
64     64   500
65     65   343
66     66   317
67     67   443
68     68   572
69     69   200
70     70   172
71     71   224
72     72   362
73     73   540
74     74   313
75     75   112
76     76   535
77     77   592
78     78   214
79     79   394
80     80   194
81     81   349

[82 rows x 2 columns]

In [77]:
# maximization problem --> we want to maximize hours/cost
prob = pulp.LpProblem('prod', pulp.LpMaximize)

In [78]:

decision_variables = []
for rownum, row in data.iterrows():
    variable = str('x' + str(rownum))
    variable = pulp.LpVariable(str(variable), lowBound = 0, upBound = 1, cat= 'Integer') #make variables binary
    decision_variables.append(variable)

print ("Total number of decision_variables: " + str(len(decision_variables)))

Total number of decision_variables: 82

In [79]:
# optimization function
total_hrs = ""
for i, hr in enumerate(decision_variables):
	total_hrs += hr

prob += total_hrs
print ("Optimization function: " + str(total_hrs))

Optimization function: x0 + x1 + x10 + x11 + x12 + x13 + x14 + x15 + x16 + x17 + x18 + x19 + x2 + x20 + x21 + x22 + x23 + x24 + x25 + x26 + x27 + x28 + x29 + x3 + x30 + x31 + x32 + x33 + x34 + x35 + x36 + x37 + x38 + x39 + x4 + x40 + x41 + x42 + x43 + x44 + x45 + x46 + x47 + x48 + x49 + x5 + x50 + x51 + x52 + x53 + x54 + x55 + x56 + x57 + x58 + x59 + x6 + x60 + x61 + x62 + x63 + x64 + x65 + x66 + x67 + x68 + x69 + x7 + x70 + x71 + x72 + x73 + x74 + x75 + x76 + x77 + x78 + x79 + x8 + x80 + x81 + x9

In [80]:
hours_week_max = 5
ratio_per_hour = 60

In [81]:
#create constrains

total_hrs_match = ""
for rownum, row in data.iterrows():
	for i, schedule in enumerate(decision_variables):
		if rownum == i:
			formula = row['hour']*schedule
			total_hrs_match += formula

capacity = 52*hours_week_max*ratio_per_hour

prob += (total_hrs_match == capacity)

In [82]:
capacity

15600

In [83]:
print(prob)
prob.writeLP("LP_test.lp" )

prod:
MAXIMIZE
1*x0 + 1*x1 + 1*x10 + 1*x11 + 1*x12 + 1*x13 + 1*x14 + 1*x15 + 1*x16 + 1*x17 + 1*x18 + 1*x19 + 1*x2 + 1*x20 + 1*x21 + 1*x22 + 1*x23 + 1*x24 + 1*x25 + 1*x26 + 1*x27 + 1*x28 + 1*x29 + 1*x3 + 1*x30 + 1*x31 + 1*x32 + 1*x33 + 1*x34 + 1*x35 + 1*x36 + 1*x37 + 1*x38 + 1*x39 + 1*x4 + 1*x40 + 1*x41 + 1*x42 + 1*x43 + 1*x44 + 1*x45 + 1*x46 + 1*x47 + 1*x48 + 1*x49 + 1*x5 + 1*x50 + 1*x51 + 1*x52 + 1*x53 + 1*x54 + 1*x55 + 1*x56 + 1*x57 + 1*x58 + 1*x59 + 1*x6 + 1*x60 + 1*x61 + 1*x62 + 1*x63 + 1*x64 + 1*x65 + 1*x66 + 1*x67 + 1*x68 + 1*x69 + 1*x7 + 1*x70 + 1*x71 + 1*x72 + 1*x73 + 1*x74 + 1*x75 + 1*x76 + 1*x77 + 1*x78 + 1*x79 + 1*x8 + 1*x80 + 1*x81 + 1*x9 + 0
SUBJECT TO
_C1: 212 x0 + 365 x1 + 295 x10 + 550 x11 + 131 x12 + 210 x13 + 523 x14
 + 211 x15 + 374 x16 + 264 x17 + 315 x18 + 345 x19 + 116 x2 + 107 x20
 + 389 x21 + 420 x22 + 560 x23 + 411 x24 + 253 x25 + 449 x26 + 404 x27
 + 409 x28 + 486 x29 + 464 x3 + 510 x30 + 588 x31 + 166 x32 + 593 x33
 + 509 x34 + 402 x35 + 542 x36 + 211 x37 + 104 x38 + 321 x39 + 174 x4
 + 349 x40 + 184 x41 + 467 x42 + 412 x43 + 238 x44 + 522 x45 + 276 x46
 + 247 x47 + 386 x48 + 462 x49 + 460 x5 + 186 x50 + 559 x51 + 252 x52
 + 320 x53 + 287 x54 + 395 x55 + 231 x56 + 479 x57 + 109 x58 + 419 x59
 + 152 x6 + 351 x60 + 236 x61 + 350 x62 + 470 x63 + 500 x64 + 343 x65
 + 317 x66 + 443 x67 + 572 x68 + 200 x69 + 126 x7 + 172 x70 + 224 x71
 + 362 x72 + 540 x73 + 313 x74 + 112 x75 + 535 x76 + 592 x77 + 214 x78
 + 394 x79 + 449 x8 + 194 x80 + 349 x81 + 541 x9 = 15600

VARIABLES
0 <= x0 <= 1 Integer
0 <= x1 <= 1 Integer
0 <= x10 <= 1 Integer
0 <= x11 <= 1 Integer
0 <= x12 <= 1 Integer
0 <= x13 <= 1 Integer
0 <= x14 <= 1 Integer
0 <= x15 <= 1 Integer
0 <= x16 <= 1 Integer
0 <= x17 <= 1 Integer
0 <= x18 <= 1 Integer
0 <= x19 <= 1 Integer
0 <= x2 <= 1 Integer
0 <= x20 <= 1 Integer
0 <= x21 <= 1 Integer
0 <= x22 <= 1 Integer
0 <= x23 <= 1 Integer
0 <= x24 <= 1 Integer
0 <= x25 <= 1 Integer
0 <= x26 <= 1 Integer
0 <= x27 <= 1 Integer
0 <= x28 <= 1 Integer
0 <= x29 <= 1 Integer
0 <= x3 <= 1 Integer
0 <= x30 <= 1 Integer
0 <= x31 <= 1 Integer
0 <= x32 <= 1 Integer
0 <= x33 <= 1 Integer
0 <= x34 <= 1 Integer
0 <= x35 <= 1 Integer
0 <= x36 <= 1 Integer
0 <= x37 <= 1 Integer
0 <= x38 <= 1 Integer
0 <= x39 <= 1 Integer
0 <= x4 <= 1 Integer
0 <= x40 <= 1 Integer
0 <= x41 <= 1 Integer
0 <= x42 <= 1 Integer
0 <= x43 <= 1 Integer
0 <= x44 <= 1 Integer
0 <= x45 <= 1 Integer
0 <= x46 <= 1 Integer
0 <= x47 <= 1 Integer
0 <= x48 <= 1 Integer
0 <= x49 <= 1 Integer
0 <= x5 <= 1 Integer
0 <= x50 <= 1 Integer
0 <= x51 <= 1 Integer
0 <= x52 <= 1 Integer
0 <= x53 <= 1 Integer
0 <= x54 <= 1 Integer
0 <= x55 <= 1 Integer
0 <= x56 <= 1 Integer
0 <= x57 <= 1 Integer
0 <= x58 <= 1 Integer
0 <= x59 <= 1 Integer
0 <= x6 <= 1 Integer
0 <= x60 <= 1 Integer
0 <= x61 <= 1 Integer
0 <= x62 <= 1 Integer
0 <= x63 <= 1 Integer
0 <= x64 <= 1 Integer
0 <= x65 <= 1 Integer
0 <= x66 <= 1 Integer
0 <= x67 <= 1 Integer
0 <= x68 <= 1 Integer
0 <= x69 <= 1 Integer
0 <= x7 <= 1 Integer
0 <= x70 <= 1 Integer
0 <= x71 <= 1 Integer
0 <= x72 <= 1 Integer
0 <= x73 <= 1 Integer
0 <= x74 <= 1 Integer
0 <= x75 <= 1 Integer
0 <= x76 <= 1 Integer
0 <= x77 <= 1 Integer
0 <= x78 <= 1 Integer
0 <= x79 <= 1 Integer
0 <= x8 <= 1 Integer
0 <= x80 <= 1 Integer
0 <= x81 <= 1 Integer
0 <= x9 <= 1 Integer

[x0,
 x1,
 x10,
 x11,
 x12,
 x13,
 x14,
 x15,
 x16,
 x17,
 x18,
 x19,
 x2,
 x20,
 x21,
 x22,
 x23,
 x24,
 x25,
 x26,
 x27,
 x28,
 x29,
 x3,
 x30,
 x31,
 x32,
 x33,
 x34,
 x35,
 x36,
 x37,
 x38,
 x39,
 x4,
 x40,
 x41,
 x42,
 x43,
 x44,
 x45,
 x46,
 x47,
 x48,
 x49,
 x5,
 x50,
 x51,
 x52,
 x53,
 x54,
 x55,
 x56,
 x57,
 x58,
 x59,
 x6,
 x60,
 x61,
 x62,
 x63,
 x64,
 x65,
 x66,
 x67,
 x68,
 x69,
 x7,
 x70,
 x71,
 x72,
 x73,
 x74,
 x75,
 x76,
 x77,
 x78,
 x79,
 x8,
 x80,
 x81,
 x9]

In [84]:
#now run optimization
optimization_result = prob.solve()
assert optimization_result == pulp.LpStatusOptimal
print("Status:", LpStatus[prob.status])
# print("Optimal Solution to the problem: ", value(prob.objective))
print ("Individual decision_variables: ")
for v in prob.variables():
	print(v.name, "=", v.varValue)

Status: Optimal
Individual decision_variables:
x0 = 1.0
x1 = 1.0
x10 = 1.0
x11 = 0.0
x12 = 1.0
x13 = 1.0
x14 = 0.0
x15 = 1.0
x16 = 0.0
x17 = 1.0
x18 = 1.0
x19 = 1.0
x2 = 1.0
x20 = 1.0
x21 = 1.0
x22 = 1.0
x23 = 0.0
x24 = 1.0
x25 = 1.0
x26 = 1.0
x27 = 1.0
x28 = 1.0
x29 = 1.0
x3 = 0.0
x30 = 0.0
x31 = 0.0
x32 = 1.0
x33 = 0.0
x34 = 0.0
x35 = 0.0
x36 = 0.0
x37 = 1.0
x38 = 1.0
x39 = 1.0
x4 = 1.0
x40 = 1.0
x41 = 1.0
x42 = 0.0
x43 = 1.0
x44 = 1.0
x45 = 0.0
x46 = 1.0
x47 = 1.0
x48 = 1.0
x49 = 0.0
x5 = 0.0
x50 = 1.0
x51 = 0.0
x52 = 1.0
x53 = 1.0
x54 = 1.0
x55 = 1.0
x56 = 1.0
x57 = 0.0
x58 = 1.0
x59 = 1.0
x6 = 1.0
x60 = 1.0
x61 = 1.0
x62 = 1.0
x63 = 0.0
x64 = 0.0
x65 = 1.0
x66 = 0.0
x67 = 0.0
x68 = 0.0
x69 = 1.0
x7 = 1.0
x70 = 1.0
x71 = 1.0
x72 = 1.0
x73 = 0.0
x74 = 1.0
x75 = 1.0
x76 = 0.0
x77 = 0.0
x78 = 1.0
x79 = 1.0
x8 = 1.0
x80 = 1.0
x81 = 1.0
x9 = 0.0

In [85]:
#reorder results
variable_name = []
variable_value = []

for v in prob.variables():
	variable_name.append(v.name)
	variable_value.append(v.varValue)

df = pd.DataFrame({'variable': variable_name, 'value': variable_value})
for rownum, row in df.iterrows():
	value = re.findall(r'(\d+)', row['variable'])
	df.loc[rownum, 'variable'] = int(value[0])

df = df.sort_values(by='variable')

#append results
for rownum, row in data.iterrows():
	for results_rownum, results_row in df.iterrows():
		if rownum == results_row['variable']:
			data.loc[rownum, 'decision'] = results_row['value']

In [87]:
data[data['decision'] == 1]

    Train  hour  decision
0       0   212       1.0
1       1   365       1.0
2       2   116       1.0
4       4   174       1.0
6       6   152       1.0
7       7   126       1.0
8       8   449       1.0
10     10   295       1.0
12     12   131       1.0
13     13   210       1.0
15     15   211       1.0
17     17   264       1.0
18     18   315       1.0
19     19   345       1.0
20     20   107       1.0
21     21   389       1.0
22     22   420       1.0
24     24   411       1.0
25     25   253       1.0
26     26   449       1.0
27     27   404       1.0
28     28   409       1.0
29     29   486       1.0
32     32   166       1.0
37     37   211       1.0
38     38   104       1.0
39     39   321       1.0
40     40   349       1.0
41     41   184       1.0
43     43   412       1.0
44     44   238       1.0
46     46   276       1.0
47     47   247       1.0
48     48   386       1.0
50     50   186       1.0
52     52   252       1.0
53     53   320       1.0
54     54   287       1.0
55     55   395       1.0
56     56   231       1.0
58     58   109       1.0
59     59   419       1.0
60     60   351       1.0
61     61   236       1.0
62     62   350       1.0
65     65   343       1.0
69     69   200       1.0
70     70   172       1.0
71     71   224       1.0
72     72   362       1.0
74     74   313       1.0
75     75   112       1.0
78     78   214       1.0
79     79   394       1.0
80     80   194       1.0
81     81   349       1.0

In [88]:
len(data[data['decision'] == 1])

56